# Form implementation generated from reading ui file 'v2.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 592)
        MainWindow.setMinimumSize(QtCore.QSize(810, 430))
        MainWindow.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(150, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_erro = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_erro.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_erro.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_erro.setFont(font)
        self.frame_erro.setStyleSheet("")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_2.setContentsMargins(200, 5, 200, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_erro)
        self.frame_12.setStyleSheet("QFrame {\n"
"    background-color: rgb(161, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.frame_erro)
        self.frame_principal = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_principal.setStyleSheet("")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_principal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_menu.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_menu)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_4.setShortcut("")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.pushButton_4)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_menu)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_corpo = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_corpo.setEnabled(True)
        self.frame_corpo.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_corpo.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"}")
        self.frame_corpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_corpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_corpo.setObjectName("frame_corpo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_corpo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_corpo)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.formulario_page = QtWidgets.QWidget()
        self.formulario_page.setObjectName("formulario_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.formulario_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_27 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_27.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_27)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.verticalLayout_9.addWidget(self.frame_27)
        self.frame_15 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_15.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Cliente_label = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Cliente_label.setFont(font)
        self.Cliente_label.setObjectName("Cliente_label")
        self.gridLayout_4.addWidget(self.Cliente_label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit.setMaxLength(50)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_3.setMaxLength(50)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_2.setMaxLength(50)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_5.setMaxLength(50)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 1, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_16.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_6.setMaxLength(50)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_7.setMaxLength(50)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 1, 2, 1, 1)
        self.Pedido_label = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pedido_label.setFont(font)
        self.Pedido_label.setObjectName("Pedido_label")
        self.gridLayout_2.addWidget(self.Pedido_label, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_4.setMaxLength(50)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_8.setMaxLength(50)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 1, 4, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_18 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setAutoFillBackground(False)
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_10.setMaxLength(50)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setAutoFillBackground(False)
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_11.setMaxLength(50)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 1, 2, 1, 1)
        self.despesas_label = QtWidgets.QLabel(parent=self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.despesas_label.setFont(font)
        self.despesas_label.setObjectName("despesas_label")
        self.gridLayout.addWidget(self.despesas_label, 0, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setAutoFillBackground(False)
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_9.setMaxLength(50)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_18)
        self.frame_17 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_17.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.frame = QtWidgets.QFrame(parent=self.frame_17)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.formulario_page)
        self.planilha_page = QtWidgets.QWidget()
        self.planilha_page.setObjectName("planilha_page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.planilha_page)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_30 = QtWidgets.QFrame(parent=self.planilha_page)
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_30.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_30)
        self.pushButton_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_17.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(parent=self.planilha_page)
        self.frame_31.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_31)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_dre = QtWidgets.QWidget()
        self.tab_dre.setObjectName("tab_dre")
        self.tabWidget.addTab(self.tab_dre, "")
        self.tab_vendas = QtWidgets.QWidget()
        self.tab_vendas.setObjectName("tab_vendas")
        self.tabWidget.addTab(self.tab_vendas, "")
        self.tab_despesas = QtWidgets.QWidget()
        self.tab_despesas.setObjectName("tab_despesas")
        self.tabWidget.addTab(self.tab_despesas, "")
        self.tab_estoque = QtWidgets.QWidget()
        self.tab_estoque.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.tab_estoque.setObjectName("tab_estoque")
        self.tabWidget.addTab(self.tab_estoque, "")
        self.verticalLayout_18.addWidget(self.tabWidget)
        self.verticalLayout_17.addWidget(self.frame_31)
        self.stackedWidget.addWidget(self.planilha_page)
        self.resumo_page = QtWidgets.QWidget()
        self.resumo_page.setObjectName("resumo_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.resumo_page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_21 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_21.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label = QtWidgets.QLabel(parent=self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.verticalLayout_12.addWidget(self.frame_21)
        self.frame_3 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_3.addWidget(self.frame_22, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.frame_20 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_20.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.gridLayout_5.addWidget(self.frame_23, 0, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.gridLayout_5.addWidget(self.frame_24, 0, 1, 1, 2)
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_5.addWidget(self.frame_25, 1, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_4.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_4.addWidget(self.frame_29)
        self.gridLayout_5.addWidget(self.frame_26, 1, 1, 1, 2)
        self.verticalLayout_12.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.resumo_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_corpo)
        self.verticalLayout.addWidget(self.frame_principal)
        self.frame_credito = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_credito.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_credito.setStyleSheet("QFrame {\n"
"    border-radius: 10px;    \n"
"}")
        self.frame_credito.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_credito.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_credito.setObjectName("frame_credito")
        self.verticalLayout.addWidget(self.frame_credito)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Myframecg"))
        self.label_4.setText(_translate("MainWindow", "Menu"))
        self.pushButton_4.setText(_translate("MainWindow", "Formulario"))
        self.pushButton_5.setText(_translate("MainWindow", "Planilha"))
        self.pushButton_6.setText(_translate("MainWindow", "Dash Board"))
        self.label_8.setText(_translate("MainWindow", "Formulario"))
        self.pushButton_8.setText(_translate("MainWindow", "  Criar DB  "))
        self.Cliente_label.setText(_translate("MainWindow", "Clientes"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Telefone"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Quantidade"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Descrição"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Valor"))
        self.Pedido_label.setText(_translate("MainWindow", "Pedidos"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Localidade"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Data "))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Uber flash"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Outros"))
        self.despesas_label.setText(_translate("MainWindow", "Despesas"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Impressão"))
        self.pushButton.setText(_translate("MainWindow", "inserir"))
        self.pushButton_2.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_3.setText(_translate("MainWindow", "Deletar"))
        self.label_5.setText(_translate("MainWindow", "Planilha"))
        self.pushButton_7.setText(_translate("MainWindow", "Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dre), _translate("MainWindow", "DRE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vendas), _translate("MainWindow", "Vendas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_despesas), _translate("MainWindow", "Despesas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_estoque), _translate("MainWindow", "Estoque"))
        self.label.setText(_translate("MainWindow", "Dash Board Vendas"))
        self.label_2.setText(_translate("MainWindow", "Vendas x mês"))
        self.label_3.setText(_translate("MainWindow", "Dados"))
        self.label_9.setText(_translate("MainWindow", "Localidade vendas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
