# Form implementation generated from reading ui file 'v2.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 592)
        MainWindow.setMinimumSize(QtCore.QSize(810, 430))
        MainWindow.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(150, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_top.setFont(font)
        self.frame_top.setStyleSheet("")
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(200, 5, 200, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_erro = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_erro.setStyleSheet("QFrame {\n"
"    background-color: rgb(161, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"}")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_erro = QtWidgets.QLabel(parent=self.frame_erro)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_erro.setFont(font)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_7.addWidget(self.label_erro)
        self.pushButton_erro = QtWidgets.QPushButton(parent=self.frame_erro)
        self.pushButton_erro.setMaximumSize(QtCore.QSize(15, 16777215))
        self.pushButton_erro.setStyleSheet("border: none;\n"
"box-shadow: none;\n"
"background-color: rgb(150, 150, 150);")
        self.pushButton_erro.setObjectName("pushButton_erro")
        self.horizontalLayout_7.addWidget(self.pushButton_erro)
        self.horizontalLayout_2.addWidget(self.frame_erro)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_principal = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_principal.setStyleSheet("")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_principal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_menu.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_menu)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_formulario = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_formulario.setEnabled(True)
        self.pushButton_formulario.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_formulario.setFont(font)
        self.pushButton_formulario.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_formulario.setShortcut("")
        self.pushButton_formulario.setCheckable(False)
        self.pushButton_formulario.setObjectName("pushButton_formulario")
        self.verticalLayout_8.addWidget(self.pushButton_formulario)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_estoque = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_estoque.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_estoque.setFont(font)
        self.pushButton_estoque.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_estoque.setObjectName("pushButton_estoque")
        self.verticalLayout_7.addWidget(self.pushButton_estoque)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_planilha = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_planilha.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_planilha.setFont(font)
        self.pushButton_planilha.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_planilha.setObjectName("pushButton_planilha")
        self.verticalLayout_6.addWidget(self.pushButton_planilha)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_menu)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_dashboard = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_dashboard.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_dashboard.setFont(font)
        self.pushButton_dashboard.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_dashboard.setObjectName("pushButton_dashboard")
        self.verticalLayout_11.addWidget(self.pushButton_dashboard)
        self.verticalLayout_10.addWidget(self.frame_5)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10.addWidget(self.frame_14)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_corpo = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_corpo.setEnabled(True)
        self.frame_corpo.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_corpo.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"}")
        self.frame_corpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_corpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_corpo.setObjectName("frame_corpo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_corpo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_corpo)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.estoque_page = QtWidgets.QWidget()
        self.estoque_page.setObjectName("estoque_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.estoque_page)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_35 = QtWidgets.QFrame(parent=self.estoque_page)
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_35.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_35)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_16.addWidget(self.frame_35)
        self.frame_19 = QtWidgets.QFrame(parent=self.estoque_page)
        self.frame_19.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_form_produto = QtWidgets.QLineEdit(parent=self.frame_19)
        self.lineEdit_form_produto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_form_produto.setObjectName("lineEdit_form_produto")
        self.gridLayout_6.addWidget(self.lineEdit_form_produto, 1, 1, 1, 1)
        self.lineEdit_form_ecomerce = QtWidgets.QLineEdit(parent=self.frame_19)
        self.lineEdit_form_ecomerce.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_form_ecomerce.setObjectName("lineEdit_form_ecomerce")
        self.gridLayout_6.addWidget(self.lineEdit_form_ecomerce, 1, 2, 1, 1)
        self.lineEdit_form_nome = QtWidgets.QLineEdit(parent=self.frame_19)
        self.lineEdit_form_nome.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_form_nome.setObjectName("lineEdit_form_nome")
        self.gridLayout_6.addWidget(self.lineEdit_form_nome, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 3, 1, 1)
        self.verticalLayout_16.addWidget(self.frame_19)
        self.frame_33 = QtWidgets.QFrame(parent=self.estoque_page)
        self.frame_33.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName("frame_33")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_33)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_33)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_form_quantidade = QtWidgets.QLineEdit(parent=self.frame_33)
        self.lineEdit_form_quantidade.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_form_quantidade.setObjectName("lineEdit_form_quantidade")
        self.gridLayout_7.addWidget(self.lineEdit_form_quantidade, 1, 0, 1, 1)
        self.lineEdit_form_valor = QtWidgets.QLineEdit(parent=self.frame_33)
        self.lineEdit_form_valor.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_form_valor.setObjectName("lineEdit_form_valor")
        self.gridLayout_7.addWidget(self.lineEdit_form_valor, 1, 1, 1, 1)
        self.lineEdit_form_data = QtWidgets.QLineEdit(parent=self.frame_33)
        self.lineEdit_form_data.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_form_data.setObjectName("lineEdit_form_data")
        self.gridLayout_7.addWidget(self.lineEdit_form_data, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 1, 3, 1, 1)
        self.verticalLayout_16.addWidget(self.frame_33)
        self.frame_32 = QtWidgets.QFrame(parent=self.estoque_page)
        self.frame_32.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_form_inserir = QtWidgets.QPushButton(parent=self.frame_32)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_form_inserir.setFont(font)
        self.pushButton_form_inserir.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_form_inserir.setObjectName("pushButton_form_inserir")
        self.horizontalLayout_10.addWidget(self.pushButton_form_inserir)
        self.pushButton_form_atualizar = QtWidgets.QPushButton(parent=self.frame_32)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_form_atualizar.setFont(font)
        self.pushButton_form_atualizar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_form_atualizar.setObjectName("pushButton_form_atualizar")
        self.horizontalLayout_10.addWidget(self.pushButton_form_atualizar)
        self.pushButton_form_deletar = QtWidgets.QPushButton(parent=self.frame_32)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_form_deletar.setFont(font)
        self.pushButton_form_deletar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_form_deletar.setObjectName("pushButton_form_deletar")
        self.horizontalLayout_10.addWidget(self.pushButton_form_deletar)
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_10.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_37.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_10.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_38.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_10.addWidget(self.frame_38)
        self.verticalLayout_16.addWidget(self.frame_32)
        self.frame_34 = QtWidgets.QFrame(parent=self.estoque_page)
        self.frame_34.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_16.addWidget(self.frame_34)
        self.stackedWidget.addWidget(self.estoque_page)
        self.formulario_page = QtWidgets.QWidget()
        self.formulario_page.setObjectName("formulario_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.formulario_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_27 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_27.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_criarBD = QtWidgets.QPushButton(parent=self.frame_27)
        self.pushButton_criarBD.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_criarBD.setObjectName("pushButton_criarBD")
        self.horizontalLayout_6.addWidget(self.pushButton_criarBD)
        self.verticalLayout_9.addWidget(self.frame_27)
        self.frame_15 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_15.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Cliente_label = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Cliente_label.setFont(font)
        self.Cliente_label.setObjectName("Cliente_label")
        self.gridLayout_4.addWidget(self.Cliente_label, 0, 0, 1, 1)
        self.lineEdit_telefone = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_telefone.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_telefone.setFont(font)
        self.lineEdit_telefone.setAutoFillBackground(False)
        self.lineEdit_telefone.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_telefone.setMaxLength(50)
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")
        self.gridLayout_4.addWidget(self.lineEdit_telefone, 1, 1, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setAutoFillBackground(False)
        self.lineEdit_email.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_email.setMaxLength(50)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout_4.addWidget(self.lineEdit_email, 1, 2, 1, 1)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_nome.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_nome.setFont(font)
        self.lineEdit_nome.setAutoFillBackground(False)
        self.lineEdit_nome.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_nome.setMaxLength(50)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout_4.addWidget(self.lineEdit_nome, 1, 0, 1, 1)
        self.lineEdit_localidade = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_localidade.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_localidade.setFont(font)
        self.lineEdit_localidade.setAutoFillBackground(False)
        self.lineEdit_localidade.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_localidade.setMaxLength(50)
        self.lineEdit_localidade.setObjectName("lineEdit_localidade")
        self.gridLayout_4.addWidget(self.lineEdit_localidade, 1, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_16.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_quantidade = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_quantidade.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_quantidade.setFont(font)
        self.lineEdit_quantidade.setAutoFillBackground(False)
        self.lineEdit_quantidade.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_quantidade.setMaxLength(50)
        self.lineEdit_quantidade.setObjectName("lineEdit_quantidade")
        self.gridLayout_2.addWidget(self.lineEdit_quantidade, 1, 1, 1, 1)
        self.lineEdit_descricao = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_descricao.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_descricao.setFont(font)
        self.lineEdit_descricao.setAutoFillBackground(False)
        self.lineEdit_descricao.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_descricao.setMaxLength(50)
        self.lineEdit_descricao.setObjectName("lineEdit_descricao")
        self.gridLayout_2.addWidget(self.lineEdit_descricao, 1, 0, 1, 1)
        self.lineEdit_valor = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_valor.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_valor.setFont(font)
        self.lineEdit_valor.setAutoFillBackground(False)
        self.lineEdit_valor.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_valor.setMaxLength(50)
        self.lineEdit_valor.setObjectName("lineEdit_valor")
        self.gridLayout_2.addWidget(self.lineEdit_valor, 1, 2, 1, 1)
        self.Pedido_label = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pedido_label.setFont(font)
        self.Pedido_label.setObjectName("Pedido_label")
        self.gridLayout_2.addWidget(self.Pedido_label, 0, 0, 1, 1)
        self.lineEdit_data = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_data.setFont(font)
        self.lineEdit_data.setAutoFillBackground(False)
        self.lineEdit_data.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_data.setMaxLength(50)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout_2.addWidget(self.lineEdit_data, 1, 4, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_18 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_uberflash = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_uberflash.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_uberflash.setFont(font)
        self.lineEdit_uberflash.setAutoFillBackground(False)
        self.lineEdit_uberflash.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_uberflash.setMaxLength(50)
        self.lineEdit_uberflash.setObjectName("lineEdit_uberflash")
        self.gridLayout.addWidget(self.lineEdit_uberflash, 1, 0, 1, 1)
        self.lineEdit_outros = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_outros.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_outros.setFont(font)
        self.lineEdit_outros.setAutoFillBackground(False)
        self.lineEdit_outros.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_outros.setMaxLength(50)
        self.lineEdit_outros.setObjectName("lineEdit_outros")
        self.gridLayout.addWidget(self.lineEdit_outros, 1, 2, 1, 1)
        self.despesas_label = QtWidgets.QLabel(parent=self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.despesas_label.setFont(font)
        self.despesas_label.setObjectName("despesas_label")
        self.gridLayout.addWidget(self.despesas_label, 0, 0, 1, 1)
        self.lineEdit_impressao = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_impressao.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_impressao.setFont(font)
        self.lineEdit_impressao.setAutoFillBackground(False)
        self.lineEdit_impressao.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_impressao.setMaxLength(50)
        self.lineEdit_impressao.setObjectName("lineEdit_impressao")
        self.gridLayout.addWidget(self.lineEdit_impressao, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_18)
        self.frame_17 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_17.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_inserir = QtWidgets.QPushButton(parent=self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_inserir.setFont(font)
        self.pushButton_inserir.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_inserir.setObjectName("pushButton_inserir")
        self.horizontalLayout_3.addWidget(self.pushButton_inserir)
        self.pushButton_atualizar = QtWidgets.QPushButton(parent=self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_atualizar.setFont(font)
        self.pushButton_atualizar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_atualizar.setObjectName("pushButton_atualizar")
        self.horizontalLayout_3.addWidget(self.pushButton_atualizar)
        self.pushButton_deletar = QtWidgets.QPushButton(parent=self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_deletar.setFont(font)
        self.pushButton_deletar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_deletar.setObjectName("pushButton_deletar")
        self.horizontalLayout_3.addWidget(self.pushButton_deletar)
        self.frame = QtWidgets.QFrame(parent=self.frame_17)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_procurar = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_procurar.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.lineEdit_procurar.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_procurar.setObjectName("lineEdit_procurar")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_procurar = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.pushButton_procurar.setFont(font)
        self.pushButton_procurar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_procurar.setObjectName("pushButton_procurar")
        self.verticalLayout_19.addWidget(self.pushButton_procurar)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.formulario_page)
        self.planilha_page = QtWidgets.QWidget()
        self.planilha_page.setObjectName("planilha_page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.planilha_page)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_30 = QtWidgets.QFrame(parent=self.planilha_page)
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_30.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_30)
        self.pushButton_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_17.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(parent=self.planilha_page)
        self.frame_31.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_31)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_dre = QtWidgets.QWidget()
        self.tab_dre.setObjectName("tab_dre")
        self.tabWidget.addTab(self.tab_dre, "")
        self.tab_vendas = QtWidgets.QWidget()
        self.tab_vendas.setObjectName("tab_vendas")
        self.tabWidget.addTab(self.tab_vendas, "")
        self.tab_despesas = QtWidgets.QWidget()
        self.tab_despesas.setObjectName("tab_despesas")
        self.tabWidget.addTab(self.tab_despesas, "")
        self.tab_estoque = QtWidgets.QWidget()
        self.tab_estoque.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.tab_estoque.setObjectName("tab_estoque")
        self.tabWidget.addTab(self.tab_estoque, "")
        self.verticalLayout_18.addWidget(self.tabWidget)
        self.verticalLayout_17.addWidget(self.frame_31)
        self.stackedWidget.addWidget(self.planilha_page)
        self.resumo_page = QtWidgets.QWidget()
        self.resumo_page.setObjectName("resumo_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.resumo_page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_21 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_21.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label = QtWidgets.QLabel(parent=self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.verticalLayout_12.addWidget(self.frame_21)
        self.frame_3 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_3.addWidget(self.frame_22, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.frame_20 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_20.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.gridLayout_5.addWidget(self.frame_23, 0, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.gridLayout_5.addWidget(self.frame_24, 0, 1, 1, 2)
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_5.addWidget(self.frame_25, 1, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_4.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_4.addWidget(self.frame_29)
        self.gridLayout_5.addWidget(self.frame_26, 1, 1, 1, 2)
        self.verticalLayout_12.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.resumo_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_corpo)
        self.verticalLayout.addWidget(self.frame_principal)
        self.frame_credito = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_credito.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_credito.setStyleSheet("QFrame {\n"
"    border-radius: 10px;    \n"
"}")
        self.frame_credito.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_credito.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_credito.setObjectName("frame_credito")
        self.verticalLayout.addWidget(self.frame_credito)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Myframecg"))
        self.label_erro.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_erro.setText(_translate("MainWindow", "X"))
        self.label_4.setText(_translate("MainWindow", "Menu"))
        self.pushButton_formulario.setText(_translate("MainWindow", "Formulario"))
        self.pushButton_estoque.setText(_translate("MainWindow", "Estoque"))
        self.pushButton_planilha.setText(_translate("MainWindow", "Planilha"))
        self.pushButton_dashboard.setText(_translate("MainWindow", "Dash Board"))
        self.label_6.setText(_translate("MainWindow", "Estoque"))
        self.label_7.setText(_translate("MainWindow", "Formecedor"))
        self.lineEdit_form_produto.setPlaceholderText(_translate("MainWindow", "Produto"))
        self.lineEdit_form_ecomerce.setPlaceholderText(_translate("MainWindow", "E-commerce"))
        self.lineEdit_form_nome.setPlaceholderText(_translate("MainWindow", "Nome "))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_form_quantidade.setPlaceholderText(_translate("MainWindow", "Quantidade"))
        self.lineEdit_form_valor.setPlaceholderText(_translate("MainWindow", "Valor"))
        self.lineEdit_form_data.setPlaceholderText(_translate("MainWindow", "Data"))
        self.pushButton_form_inserir.setText(_translate("MainWindow", "Inserir"))
        self.pushButton_form_atualizar.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_form_deletar.setText(_translate("MainWindow", "Deletar"))
        self.label_8.setText(_translate("MainWindow", "Formulario"))
        self.pushButton_criarBD.setText(_translate("MainWindow", "  Criar BD  "))
        self.Cliente_label.setText(_translate("MainWindow", "Clientes"))
        self.lineEdit_telefone.setPlaceholderText(_translate("MainWindow", "Telefone"))
        self.lineEdit_email.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.lineEdit_nome.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEdit_localidade.setPlaceholderText(_translate("MainWindow", "Localidade"))
        self.lineEdit_quantidade.setPlaceholderText(_translate("MainWindow", "Quantidade 1"))
        self.lineEdit_descricao.setPlaceholderText(_translate("MainWindow", "Descrição"))
        self.lineEdit_valor.setPlaceholderText(_translate("MainWindow", "Valor 65,00"))
        self.Pedido_label.setText(_translate("MainWindow", "Pedidos"))
        self.lineEdit_data.setPlaceholderText(_translate("MainWindow", "Data 29/03/2023"))
        self.lineEdit_uberflash.setPlaceholderText(_translate("MainWindow", "Uber flash 5,00"))
        self.lineEdit_outros.setPlaceholderText(_translate("MainWindow", "Outros"))
        self.despesas_label.setText(_translate("MainWindow", "Despesas"))
        self.lineEdit_impressao.setPlaceholderText(_translate("MainWindow", "Impressão 1,50"))
        self.pushButton_inserir.setText(_translate("MainWindow", "inserir"))
        self.pushButton_atualizar.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_deletar.setText(_translate("MainWindow", "Deletar"))
        self.lineEdit_procurar.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.pushButton_procurar.setText(_translate("MainWindow", "Procurar"))
        self.label_5.setText(_translate("MainWindow", "Planilha"))
        self.pushButton_7.setText(_translate("MainWindow", "  Excel  "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dre), _translate("MainWindow", "DRE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vendas), _translate("MainWindow", "Vendas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_despesas), _translate("MainWindow", "Despesas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_estoque), _translate("MainWindow", "Estoque"))
        self.label.setText(_translate("MainWindow", "Dash Board Vendas"))
        self.label_2.setText(_translate("MainWindow", "Vendas x mês"))
        self.label_3.setText(_translate("MainWindow", "Dados"))
        self.label_9.setText(_translate("MainWindow", "Localidade vendas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
