# Form implementation generated from reading ui file 'v3.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 567)
        MainWindow.setMinimumSize(QtCore.QSize(810, 430))
        MainWindow.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(150, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_top.setFont(font)
        self.frame_top.setStyleSheet("")
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(200, 5, 200, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_erro = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_erro.setStyleSheet("QFrame {\n"
"    background-color: rgb(161, 0, 0);\n"
"    border-radius: 5px;\n"
"\n"
"}")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_7.setContentsMargins(5, 0, 9, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_erro = QtWidgets.QLabel(parent=self.frame_erro)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_erro.setFont(font)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_7.addWidget(self.label_erro)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_erro)
        self.pushButton.setMaximumSize(QtCore.QSize(15, 16777215))
        self.pushButton.setStyleSheet("background-color: rgb(208, 208, 0);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame_erro)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_principal = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_principal.setStyleSheet("")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_principal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_menu.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_menu)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_formulario = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_formulario.setEnabled(True)
        self.pushButton_formulario.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_formulario.setFont(font)
        self.pushButton_formulario.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_formulario.setShortcut("")
        self.pushButton_formulario.setCheckable(False)
        self.pushButton_formulario.setObjectName("pushButton_formulario")
        self.verticalLayout_8.addWidget(self.pushButton_formulario)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_planilha = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_planilha.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_planilha.setFont(font)
        self.pushButton_planilha.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_planilha.setObjectName("pushButton_planilha")
        self.verticalLayout_7.addWidget(self.pushButton_planilha)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_dashboard = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_dashboard.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_dashboard.setFont(font)
        self.pushButton_dashboard.setStyleSheet("border: none;\n"
"box-shadow: none;")
        self.pushButton_dashboard.setObjectName("pushButton_dashboard")
        self.verticalLayout_6.addWidget(self.pushButton_dashboard)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_menu)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10.addWidget(self.frame_5)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10.addWidget(self.frame_14)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_corpo = QtWidgets.QFrame(parent=self.frame_principal)
        self.frame_corpo.setEnabled(True)
        self.frame_corpo.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_corpo.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"}")
        self.frame_corpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_corpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_corpo.setObjectName("frame_corpo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_corpo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_corpo)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.estoque_page = QtWidgets.QWidget()
        self.estoque_page.setObjectName("estoque_page")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.estoque_page)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.stackedWidget.addWidget(self.estoque_page)
        self.formulario_page = QtWidgets.QWidget()
        self.formulario_page.setObjectName("formulario_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.formulario_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_27 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_27.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton_criarBD_2 = QtWidgets.QPushButton(parent=self.frame_27)
        self.pushButton_criarBD_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_criarBD_2.setObjectName("pushButton_criarBD_2")
        self.horizontalLayout_8.addWidget(self.pushButton_criarBD_2)
        self.verticalLayout_9.addWidget(self.frame_27)
        self.frame_15 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_15.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_nome_2 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_nome_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_nome_2.setFont(font)
        self.lineEdit_nome_2.setAutoFillBackground(False)
        self.lineEdit_nome_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_nome_2.setMaxLength(50)
        self.lineEdit_nome_2.setObjectName("lineEdit_nome_2")
        self.gridLayout_6.addWidget(self.lineEdit_nome_2, 2, 0, 1, 1)
        self.Cliente_label_2 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Cliente_label_2.setFont(font)
        self.Cliente_label_2.setObjectName("Cliente_label_2")
        self.gridLayout_6.addWidget(self.Cliente_label_2, 0, 0, 1, 1)
        self.lineEdit_telefone_2 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_telefone_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_telefone_2.setFont(font)
        self.lineEdit_telefone_2.setAutoFillBackground(False)
        self.lineEdit_telefone_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_telefone_2.setMaxLength(50)
        self.lineEdit_telefone_2.setObjectName("lineEdit_telefone_2")
        self.gridLayout_6.addWidget(self.lineEdit_telefone_2, 2, 1, 1, 1)
        self.lineEdit_email_2 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_email_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_email_2.setFont(font)
        self.lineEdit_email_2.setAutoFillBackground(False)
        self.lineEdit_email_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_email_2.setMaxLength(50)
        self.lineEdit_email_2.setObjectName("lineEdit_email_2")
        self.gridLayout_6.addWidget(self.lineEdit_email_2, 2, 2, 1, 1)
        self.lineEdit_localidade_2 = QtWidgets.QLineEdit(parent=self.frame_15)
        self.lineEdit_localidade_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_localidade_2.setFont(font)
        self.lineEdit_localidade_2.setAutoFillBackground(False)
        self.lineEdit_localidade_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_localidade_2.setMaxLength(50)
        self.lineEdit_localidade_2.setObjectName("lineEdit_localidade_2")
        self.gridLayout_6.addWidget(self.lineEdit_localidade_2, 2, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_16.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_quantidade_3 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_quantidade_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_quantidade_3.setFont(font)
        self.lineEdit_quantidade_3.setAutoFillBackground(False)
        self.lineEdit_quantidade_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_quantidade_3.setMaxLength(50)
        self.lineEdit_quantidade_3.setObjectName("lineEdit_quantidade_3")
        self.gridLayout_11.addWidget(self.lineEdit_quantidade_3, 1, 1, 1, 1)
        self.lineEdit_descricao_3 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_descricao_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_descricao_3.setFont(font)
        self.lineEdit_descricao_3.setAutoFillBackground(False)
        self.lineEdit_descricao_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_descricao_3.setMaxLength(50)
        self.lineEdit_descricao_3.setObjectName("lineEdit_descricao_3")
        self.gridLayout_11.addWidget(self.lineEdit_descricao_3, 1, 0, 1, 1)
        self.lineEdit_valor_3 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_valor_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_valor_3.setFont(font)
        self.lineEdit_valor_3.setAutoFillBackground(False)
        self.lineEdit_valor_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_valor_3.setMaxLength(50)
        self.lineEdit_valor_3.setObjectName("lineEdit_valor_3")
        self.gridLayout_11.addWidget(self.lineEdit_valor_3, 1, 2, 1, 1)
        self.Pedido_label_3 = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pedido_label_3.setFont(font)
        self.Pedido_label_3.setObjectName("Pedido_label_3")
        self.gridLayout_11.addWidget(self.Pedido_label_3, 0, 0, 1, 1)
        self.lineEdit_data_3 = QtWidgets.QLineEdit(parent=self.frame_16)
        self.lineEdit_data_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_data_3.setFont(font)
        self.lineEdit_data_3.setAutoFillBackground(False)
        self.lineEdit_data_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_data_3.setMaxLength(50)
        self.lineEdit_data_3.setObjectName("lineEdit_data_3")
        self.gridLayout_11.addWidget(self.lineEdit_data_3, 1, 4, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_18 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_uberflash_2 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_uberflash_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_uberflash_2.setFont(font)
        self.lineEdit_uberflash_2.setAutoFillBackground(False)
        self.lineEdit_uberflash_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_uberflash_2.setMaxLength(50)
        self.lineEdit_uberflash_2.setObjectName("lineEdit_uberflash_2")
        self.gridLayout_9.addWidget(self.lineEdit_uberflash_2, 3, 0, 1, 1)
        self.lineEdit_outros_2 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_outros_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_outros_2.setFont(font)
        self.lineEdit_outros_2.setAutoFillBackground(False)
        self.lineEdit_outros_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_outros_2.setMaxLength(50)
        self.lineEdit_outros_2.setObjectName("lineEdit_outros_2")
        self.gridLayout_9.addWidget(self.lineEdit_outros_2, 3, 2, 1, 1)
        self.despesas_label_2 = QtWidgets.QLabel(parent=self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.despesas_label_2.setFont(font)
        self.despesas_label_2.setObjectName("despesas_label_2")
        self.gridLayout_9.addWidget(self.despesas_label_2, 0, 0, 1, 1)
        self.lineEdit_impressao_2 = QtWidgets.QLineEdit(parent=self.frame_18)
        self.lineEdit_impressao_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_impressao_2.setFont(font)
        self.lineEdit_impressao_2.setAutoFillBackground(False)
        self.lineEdit_impressao_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_impressao_2.setMaxLength(50)
        self.lineEdit_impressao_2.setObjectName("lineEdit_impressao_2")
        self.gridLayout_9.addWidget(self.lineEdit_impressao_2, 3, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_18)
        self.frame = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineEdit_status_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_status_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_status_2.setObjectName("lineEdit_status_2")
        self.gridLayout_10.addWidget(self.lineEdit_status_2, 1, 0, 1, 1)
        self.pushButton_procurar_21 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_procurar_21.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_procurar_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.pushButton_procurar_21.setFont(font)
        self.pushButton_procurar_21.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_procurar_21.setObjectName("pushButton_procurar_21")
        self.gridLayout_10.addWidget(self.pushButton_procurar_21, 1, 3, 1, 1)
        self.lineEdit_procurar_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_procurar_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_procurar_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"    background-color: rgb(30,30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.lineEdit_procurar_2.setObjectName("lineEdit_procurar_2")
        self.gridLayout_10.addWidget(self.lineEdit_procurar_2, 1, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.frame)
        self.frame_17 = QtWidgets.QFrame(parent=self.formulario_page)
        self.frame_17.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_inserir_2 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_inserir_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_inserir_2.setFont(font)
        self.pushButton_inserir_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_inserir_2.setObjectName("pushButton_inserir_2")
        self.horizontalLayout_9.addWidget(self.pushButton_inserir_2)
        self.pushButton_atualizar_2 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_atualizar_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_atualizar_2.setFont(font)
        self.pushButton_atualizar_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_atualizar_2.setObjectName("pushButton_atualizar_2")
        self.horizontalLayout_9.addWidget(self.pushButton_atualizar_2)
        self.pushButton_deletar_2 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_deletar_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_deletar_2.setFont(font)
        self.pushButton_deletar_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_deletar_2.setObjectName("pushButton_deletar_2")
        self.horizontalLayout_9.addWidget(self.pushButton_deletar_2)
        spacerItem2 = QtWidgets.QSpacerItem(80, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.pushButton_custo_fixo_2 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_custo_fixo_2.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_custo_fixo_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_custo_fixo_2.setObjectName("pushButton_custo_fixo_2")
        self.horizontalLayout_9.addWidget(self.pushButton_custo_fixo_2)
        self.pushButton_estoque_2 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_estoque_2.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_estoque_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_estoque_2.setObjectName("pushButton_estoque_2")
        self.horizontalLayout_9.addWidget(self.pushButton_estoque_2)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.formulario_page)
        self.planilha_page = QtWidgets.QWidget()
        self.planilha_page.setObjectName("planilha_page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.planilha_page)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_30 = QtWidgets.QFrame(parent=self.planilha_page)
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_30.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_plan_label = QtWidgets.QLabel(parent=self.frame_30)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_plan_label.setFont(font)
        self.label_plan_label.setObjectName("label_plan_label")
        self.horizontalLayout_5.addWidget(self.label_plan_label)
        self.pushButton_plan_atualizar = QtWidgets.QPushButton(parent=self.frame_30)
        self.pushButton_plan_atualizar.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_plan_atualizar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.pushButton_plan_atualizar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_plan_atualizar.setObjectName("pushButton_plan_atualizar")
        self.horizontalLayout_5.addWidget(self.pushButton_plan_atualizar)
        self.pushButton_baixar = QtWidgets.QPushButton(parent=self.frame_30)
        self.pushButton_baixar.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_baixar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.pushButton_baixar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(161, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_baixar.setObjectName("pushButton_baixar")
        self.horizontalLayout_5.addWidget(self.pushButton_baixar)
        self.verticalLayout_17.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(parent=self.planilha_page)
        self.frame_31.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget_planilha = QtWidgets.QTabWidget(parent=self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.tabWidget_planilha.setFont(font)
        self.tabWidget_planilha.setObjectName("tabWidget_planilha")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.tableWidget_dre = QtWidgets.QTableWidget(parent=self.tab_3)
        self.tableWidget_dre.setObjectName("tableWidget_dre")
        self.tableWidget_dre.setColumnCount(13)
        self.tableWidget_dre.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dre.setHorizontalHeaderItem(12, item)
        self.verticalLayout_23.addWidget(self.tableWidget_dre)
        self.tabWidget_planilha.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.tableWidget_planilha_cliente = QtWidgets.QTableWidget(parent=self.tab_4)
        self.tableWidget_planilha_cliente.setColumnCount(5)
        self.tableWidget_planilha_cliente.setObjectName("tableWidget_planilha_cliente")
        self.tableWidget_planilha_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_cliente.setHorizontalHeaderItem(4, item)
        self.tableWidget_planilha_cliente.horizontalHeader().setDefaultSectionSize(95)
        self.verticalLayout_21.addWidget(self.tableWidget_planilha_cliente)
        self.tabWidget_planilha.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tableWidget_planilha_estoque = QtWidgets.QTableWidget(parent=self.tab_5)
        self.tableWidget_planilha_estoque.setObjectName("tableWidget_planilha_estoque")
        self.tableWidget_planilha_estoque.setColumnCount(4)
        self.tableWidget_planilha_estoque.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_estoque.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_estoque.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_estoque.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_planilha_estoque.setHorizontalHeaderItem(3, item)
        self.verticalLayout_22.addWidget(self.tableWidget_planilha_estoque)
        self.tabWidget_planilha.addTab(self.tab_5, "")
        self.verticalLayout_18.addWidget(self.tabWidget_planilha)
        self.verticalLayout_17.addWidget(self.frame_31)
        self.stackedWidget.addWidget(self.planilha_page)
        self.resumo_page = QtWidgets.QWidget()
        self.resumo_page.setObjectName("resumo_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.resumo_page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_21 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_21.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label = QtWidgets.QLabel(parent=self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.verticalLayout_12.addWidget(self.frame_21)
        self.frame_3 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_vendas_mes = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_vendas_mes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_vendas_mes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_vendas_mes.setObjectName("frame_vendas_mes")
        self.gridLayout_3.addWidget(self.frame_vendas_mes, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.frame_20 = QtWidgets.QFrame(parent=self.resumo_page)
        self.frame_20.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.gridLayout_5.addWidget(self.frame_23, 0, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.gridLayout_5.addWidget(self.frame_24, 0, 1, 1, 2)
        self.frame_dados = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_dados.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_dados.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_dados.setObjectName("frame_dados")
        self.formLayout = QtWidgets.QFormLayout(self.frame_dados)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_dados)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.venda_label = QtWidgets.QLabel(parent=self.frame_dados)
        self.venda_label.setObjectName("venda_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.venda_label)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_dados)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.compra_label = QtWidgets.QLabel(parent=self.frame_dados)
        self.compra_label.setObjectName("compra_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.compra_label)
        self.gridLayout_5.addWidget(self.frame_dados, 1, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_localidade_vendas = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_localidade_vendas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_localidade_vendas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_localidade_vendas.setObjectName("frame_localidade_vendas")
        self.horizontalLayout_4.addWidget(self.frame_localidade_vendas)
        self.frame_localidades_vendas_2 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_localidades_vendas_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_localidades_vendas_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_localidades_vendas_2.setObjectName("frame_localidades_vendas_2")
        self.horizontalLayout_4.addWidget(self.frame_localidades_vendas_2)
        self.gridLayout_5.addWidget(self.frame_26, 1, 1, 1, 2)
        self.verticalLayout_12.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.resumo_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_corpo)
        self.verticalLayout.addWidget(self.frame_principal)
        self.frame_credito = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_credito.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_credito.setStyleSheet("QFrame {\n"
"    border-radius: 10px;    \n"
"}")
        self.frame_credito.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_credito.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_credito.setObjectName("frame_credito")
        self.verticalLayout.addWidget(self.frame_credito)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget_planilha.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Myframecg"))
        self.label_erro.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "x"))
        self.label_4.setText(_translate("MainWindow", "Menu"))
        self.pushButton_formulario.setText(_translate("MainWindow", "Formulario"))
        self.pushButton_planilha.setText(_translate("MainWindow", "Planilha"))
        self.pushButton_dashboard.setText(_translate("MainWindow", "Dash Board"))
        self.label_10.setText(_translate("MainWindow", "Venda"))
        self.pushButton_criarBD_2.setText(_translate("MainWindow", "  Criar BD  "))
        self.lineEdit_nome_2.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.Cliente_label_2.setText(_translate("MainWindow", "Cliente"))
        self.lineEdit_telefone_2.setPlaceholderText(_translate("MainWindow", "Telefone"))
        self.lineEdit_email_2.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.lineEdit_localidade_2.setPlaceholderText(_translate("MainWindow", "Localidade"))
        self.lineEdit_quantidade_3.setPlaceholderText(_translate("MainWindow", "Quantidade 1"))
        self.lineEdit_descricao_3.setPlaceholderText(_translate("MainWindow", "Descrição"))
        self.lineEdit_valor_3.setPlaceholderText(_translate("MainWindow", "Valor 65,00"))
        self.Pedido_label_3.setText(_translate("MainWindow", "Pedido"))
        self.lineEdit_data_3.setPlaceholderText(_translate("MainWindow", "Data 29/03/2023"))
        self.lineEdit_uberflash_2.setPlaceholderText(_translate("MainWindow", "Uber flash 5,00"))
        self.lineEdit_outros_2.setPlaceholderText(_translate("MainWindow", "Outros"))
        self.despesas_label_2.setText(_translate("MainWindow", "Despesa"))
        self.lineEdit_impressao_2.setPlaceholderText(_translate("MainWindow", "Impressão 1,50"))
        self.label_14.setText(_translate("MainWindow", "Status"))
        self.lineEdit_status_2.setPlaceholderText(_translate("MainWindow", "Concluido"))
        self.pushButton_procurar_21.setText(_translate("MainWindow", "Procurar"))
        self.lineEdit_procurar_2.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.pushButton_inserir_2.setText(_translate("MainWindow", "inserir"))
        self.pushButton_atualizar_2.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_deletar_2.setText(_translate("MainWindow", "Deletar"))
        self.pushButton_custo_fixo_2.setText(_translate("MainWindow", "Custo Fixo"))
        self.pushButton_estoque_2.setText(_translate("MainWindow", "Estoque"))
        self.label_5.setText(_translate("MainWindow", "Planilha"))
        self.label_plan_label.setText(_translate("MainWindow", "00 Quadros Pendente e 00 Quadros Concluidos"))
        self.pushButton_plan_atualizar.setText(_translate("MainWindow", "Atualizar"))
        self.pushButton_baixar.setText(_translate("MainWindow", "Baixar Excel"))
        item = self.tableWidget_dre.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Descrição"))
        item = self.tableWidget_dre.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Janeiro"))
        item = self.tableWidget_dre.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fevereiro"))
        item = self.tableWidget_dre.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Março"))
        item = self.tableWidget_dre.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Abril"))
        item = self.tableWidget_dre.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Maio"))
        item = self.tableWidget_dre.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Junho"))
        item = self.tableWidget_dre.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Julho"))
        item = self.tableWidget_dre.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Agosto"))
        item = self.tableWidget_dre.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Setembro"))
        item = self.tableWidget_dre.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Outubro"))
        item = self.tableWidget_dre.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Novembro"))
        item = self.tableWidget_dre.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Dezembro"))
        self.tabWidget_planilha.setTabText(self.tabWidget_planilha.indexOf(self.tab_3), _translate("MainWindow", "DRE"))
        item = self.tableWidget_planilha_cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget_planilha_cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Whats-app"))
        item = self.tableWidget_planilha_cliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Localidade"))
        item = self.tableWidget_planilha_cliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data prazo"))
        item = self.tableWidget_planilha_cliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Situação"))
        self.tabWidget_planilha.setTabText(self.tabWidget_planilha.indexOf(self.tab_4), _translate("MainWindow", "Venda"))
        item = self.tableWidget_planilha_estoque.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fornecedor"))
        item = self.tableWidget_planilha_estoque.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Produto"))
        item = self.tableWidget_planilha_estoque.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantidade"))
        item = self.tableWidget_planilha_estoque.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "E-commerce"))
        self.tabWidget_planilha.setTabText(self.tabWidget_planilha.indexOf(self.tab_5), _translate("MainWindow", "Estoque"))
        self.label.setText(_translate("MainWindow", "Dash Board Vendas"))
        self.label_2.setText(_translate("MainWindow", "Vendas x mês"))
        self.label_3.setText(_translate("MainWindow", "Dados"))
        self.label_9.setText(_translate("MainWindow", "Localidade vendas"))
        self.label_11.setText(_translate("MainWindow", "Venda total:"))
        self.venda_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "Compra total:"))
        self.compra_label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
