# Form implementation generated from reading ui file 'v6.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_estoque(object):
    def setupUi(self, MainWindow_estoque):
        MainWindow_estoque.setObjectName("MainWindow_estoque")
        MainWindow_estoque.resize(410, 165)
        MainWindow_estoque.setMinimumSize(QtCore.QSize(405, 160))
        MainWindow_estoque.setMaximumSize(QtCore.QSize(410, 165))
        MainWindow_estoque.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_estoque)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 411, 171))
        self.frame.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_ok = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.gridLayout.addWidget(self.pushButton_ok, 1, 1, 1, 1)
        self.label_pop_up = QtWidgets.QLabel(parent=self.frame)
        self.label_pop_up.setObjectName("label_pop_up")
        self.gridLayout.addWidget(self.label_pop_up, 0, 1, 1, 3)
        self.pushButton_cancelar = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.gridLayout.addWidget(self.pushButton_cancelar, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 4, 1, 1)
        MainWindow_estoque.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_estoque)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_estoque)

    def retranslateUi(self, MainWindow_estoque):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_estoque.setWindowTitle(_translate("MainWindow_estoque", "Myframecg"))
        self.pushButton_ok.setText(_translate("MainWindow_estoque", "OK"))
        self.label_pop_up.setText(_translate("MainWindow_estoque", "TextLabel"))
        self.pushButton_cancelar.setText(_translate("MainWindow_estoque", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_estoque = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_estoque()
    ui.setupUi(MainWindow_estoque)
    MainWindow_estoque.show()
    sys.exit(app.exec())
